# Generated by Django 5.2 on 2025-04-10 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.DateField()),
                ('mode', models.CharField(choices=[('reality', 'Reality'), ('cyber', 'Cyber')], max_length=10)),
                ('xp', models.IntegerField(default=0)),
                ('layer', models.CharField(default='RL1', max_length=10)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
