# Generated by Django 5.2 on 2025-04-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.DateField()),
                ('mode', models.CharField(choices=[('reality', 'Reality'), ('cyber', 'Cyber')], max_length=10)),
                ('xp', models.IntegerField(default=0)),
                ('layer', models.CharField(default='RL1', max_length=10)),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
